### PR TITLE
Add custom favicon

### PR DESCRIPTION
**Pull request by nisrulz**
Adds ability to set custom favicon

### CODE REVIEW

**Comment by zzossig** [comment]
Hi, Thanks for the pull request but I don't understand why this code is required

**Comment by zzossig** [comment]
You can override the default favicon by putting your favicon at root/static folder

**Comment by nisrulz** [comment]
You are right. I couldn't get it to work. There is no info around how to set it up, so I just kind of tried to fix it by own way.

I think I will open up an issue if I can't get it to work right away. I appreciate the extensive readme you have written but some stuff is not straight forward. 

I took the `exampleSite` folder itself and tried to build it that way, still some stuff didn't work. 

I cannot get the header background to change either :man_shrugging:

**Comment by zzossig** [comment]
Ok, feel free to open a new issue.
And I'll check the readme soon.

**Pull request closed without merging**
