### PR TITLE
Make featured image a link to article

### PR DESCRIPTION
**Pull request by BGnoinski**
Removes the scoped variables in with() so that we can use  {{ .Permalink }} and make the image a link to the article.

### CODE REVIEW

**Comment by zzossig** [comment]
Hugo not found image in my end. I'll look into it

**Comment by zzossig** [comment]
@BGnoinski Can you check the link works correctly?

**Comment by BGnoinski** [comment]
@zzossig Links definitely work on my end.

Screenshot from 2019-11-15 06-01-18

Screenshot from 2019-11-15 06-01-35

Can you post the image link that your picture is trying to use?

**Comment by BGnoinski** [comment]
Oh, the default test site is looking for `http://localhost:35193/en/images/tree.jpg` but I have the `en` disabled via `defaultContentLanguageInSubdir = false`

And I just confirmed with the test site that with  `defaultContentLanguageInSubdir = false` the image loads correctly.

I think the Language subdir will need to exclude images, unless your intent is to have different images for each language?

**Comment by zzossig** [comment]
Hmm, I'll investigate more to support them all no matter that is true or false.

**Pull request closed without merging**
